eureka.instance.hostname=localhost

#as this is server application so below property will be false
eureka.client.register-with-eureka=false
#as this is server application we don't need copy of registered service's list
eureka.client.fetch-registry=false

server.port=8761